name: 'Reusable Terraform Security Scan'

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory containing Terraform files'
        required: true
        type: string

permissions:
  contents: read

jobs:
  terraform-security-scan:
    name: 'Terraform Security Scan'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.6.0'  # Fixed version
        
    - name: Terraform Init
      run: |
        cd ${{ inputs.working_directory }}
        terraform init -backend=false
        
    - name: Run Checkov Scan
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.working_directory }}
        framework: terraform
        output_format: cli
        soft_fail: true  # Don't fail on warnings
        skip_check: CKV_TF_1

    - name: Run Trivy Config Scan
      id: trivy
      run: |
        cd ${{ inputs.working_directory }}
        trivy config --tf-vars terraform.tfvars --tf-vars global.auto.tfvars --severity HIGH,CRITICAL --format table .
      continue-on-error: true  # Don't fail on warnings
        
    - name: Security Scan Summary
      if: always()
      run: |
        echo "Security scans completed for directory: ${{ inputs.working_directory }}"
        echo "Checkov scan status: ${{ steps.checkov.outcome }}"
        echo "Trivy scan status: ${{ steps.trivy.outcome }}"
        echo "Note: Results are available in the job logs above. SARIF upload disabled (requires GitHub Advanced Security)." 