name: 'Reusable Terraform Security Scan'

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory containing Terraform files'
        required: true
        type: string

permissions:
  contents: read

jobs:
  terraform-security-scan:
    name: 'Terraform Security Scan'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
        
    - name: Run Checkov Scan
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ${{ inputs.working_directory }}
        framework: terraform
        output_format: cli
        soft_fail: true  # Don't fail on warnings
        skip_check: CKV_TF_1
        
    - name: Security Scan Summary
      if: always()
      run: |
        echo "Checkov security scan completed for directory: ${{ inputs.working_directory }}"
        echo "Checkov scan status: ${{ steps.checkov.outcome }}" 