name: 'Reusable Trivy Scan'

on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Directory containing Terraform plan file'
        required: true
        type: string
      plan_file:
        description: 'Name of the Terraform plan file (without path)'
        required: false
        type: string
        default: 'tfplan'

permissions:
  contents: read

jobs:
  trivy-scan:
    name: 'Trivy Security Scan'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.6.0'
        
    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

    - name: Convert Plan to JSON
      run: |
        cd ${{ inputs.working_directory }}
        terraform show -json ${{ inputs.plan_file }} > tfplan.json
        
    - name: Run Trivy scan on Terraform plan
      run: |
        cd ${{ inputs.working_directory }}
        trivy config tfplan.json --format table
        
    - name: Publish Trivy Output to Summary
      run: |
        cd ${{ inputs.working_directory }}
        if [[ -f tfplan.json ]]; then
          trivy config tfplan.json --format table > trivy-summary.txt
          {
            echo "### Trivy Security Scan Results"
            echo "<details><summary>Click to expand</summary>"
            echo ""
            echo '```'
            cat trivy-summary.txt
            echo '```'
            echo "</details>"
          } >> $GITHUB_STEP_SUMMARY
        fi
        
    - name: Trivy Scan Summary
      if: always()
      run: |
        echo "Trivy security scan completed for directory: ${{ inputs.working_directory }}"
        echo "Scanned plan file: ${{ inputs.plan_file }}" 